# Generated by Django 6.0.5 on 2026-05-13 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0168_consolidate_visibility_booleans"),
        ("iam", "0021_fix_auditee_iam_groups"),
        ("pmbok", "0005_responsibilitymatrix_responsibilityactivity_and_more"),
        ("resilience", "0007_doraincidentreport"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResponsibilityActivity",
            new_name="ResponsibilityMatrixActivity",
        ),
    ]
