# Generated by Django 6.0.4 on 2026-04-30 06:47

import core.validators
import django.db.models.deletion
import iam.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0167_backfill_respondent_alignment"),
        ("iam", "0021_fix_auditee_iam_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencerevision",
            name="manifest_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA256 of sorted file hashes; identifies the bundle as a whole.",
                max_length=64,
                null=True,
                verbose_name="Manifest hash",
            ),
        ),
        migrations.AddField(
            model_name="evidencerevision",
            name="review_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evidencerevision",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evidencerevision",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_evidence_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evidencerevision",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("missing", "Missing"),
                    ("in_review", "In review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="evidencerevision",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_evidence_revisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to="",
                        validators=[
                            core.validators.validate_file_size,
                            core.validators.validate_file_name,
                        ],
                    ),
                ),
                ("original_name", models.CharField(blank=True, max_length=500)),
                ("sha256", models.CharField(blank=True, db_index=True, max_length=64)),
                ("size", models.BigIntegerField(default=0)),
                ("ordering", models.PositiveSmallIntegerField(default=0)),
                (
                    "folder",
                    models.ForeignKey(
                        default=iam.models.Folder.get_root_folder_id,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_folder",
                        to="iam.folder",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.evidencerevision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence File",
                "verbose_name_plural": "Evidence Files",
                "ordering": ["ordering", "created_at"],
            },
        ),
    ]
